// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcJh9B0cyJHaP1o_yb45u1Y0-bEFkjVe8',
    appId: '1:90653799471:web:feee0151a5277cab0882da',
    messagingSenderId: '90653799471',
    projectId: 'projeto-listadetarefa',
    authDomain: 'projeto-listadetarefa.firebaseapp.com',
    databaseURL: 'https://projeto-listadetarefa-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-listadetarefa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAojp5sgdJL6dyiM0En4fZncQXNNR8ieM0',
    appId: '1:90653799471:android:1c0aae6d890d6f680882da',
    messagingSenderId: '90653799471',
    projectId: 'projeto-listadetarefa',
    databaseURL: 'https://projeto-listadetarefa-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-listadetarefa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMSbQbiP8TQQhcHmRMNzhWVSqLNYHJSZc',
    appId: '1:90653799471:ios:878a6d1faa72b5230882da',
    messagingSenderId: '90653799471',
    projectId: 'projeto-listadetarefa',
    databaseURL: 'https://projeto-listadetarefa-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-listadetarefa.firebasestorage.app',
    iosBundleId: 'com.example.projeto02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMSbQbiP8TQQhcHmRMNzhWVSqLNYHJSZc',
    appId: '1:90653799471:ios:878a6d1faa72b5230882da',
    messagingSenderId: '90653799471',
    projectId: 'projeto-listadetarefa',
    databaseURL: 'https://projeto-listadetarefa-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-listadetarefa.firebasestorage.app',
    iosBundleId: 'com.example.projeto02',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcJh9B0cyJHaP1o_yb45u1Y0-bEFkjVe8',
    appId: '1:90653799471:web:4621cf46b195cd400882da',
    messagingSenderId: '90653799471',
    projectId: 'projeto-listadetarefa',
    authDomain: 'projeto-listadetarefa.firebaseapp.com',
    databaseURL: 'https://projeto-listadetarefa-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-listadetarefa.firebasestorage.app',
  );
}
